CPPFLAGS = -g -O0 -DDUG

thread:
        g++ createThread.cpp -o createThread --std=c++11 -pthread

mutex:
        g++ createMutex.cpp -o createMutex --std=c++11 -pthread

Condition:
        g++ createCondition.cpp -o createCondition --std=c++11 -pthread

clean:
        rm create*
